sudo: false
language: Java
jdk: oraclejdk8
install: mvn install -DskipTests -DskipITs -q 
script: mvn clean verify && mvn cobertura:cobertura-integration-test coveralls:report
# Run Sonar analysis only after a successful build to avoid incomplete results
after_success:
  - >
    if [ ${TRAVIS_PULL_REQUEST} == "false" ] && [ ${TRAVIS_BRANCH} == "develop" ]; then
    mvn sonar:sonar -Dsonar.host.url=https://repository.kaazing.com/secret-sauce/sonarqube -Dsonar.login=travis -Dsonar.password=kaazing;
    else
    echo "SonarQube analysis is performed only for commits on the develop branch(not for PRs)";
    fi;
